# Generated by Django 2.2.4 on 2019-08-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20190812_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='named',
            field=models.TextField(blank=True, null=True, verbose_name='Фамилия и имя'),
        ),
        migrations.AddField(
            model_name='bb',
            name='phone',
            field=models.FloatField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
